spring:
  application:
    name: spring-boot-client
  boot:
    admin:
      client:
        url: http://spring-boot-admin-server:8888

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always


info:
  app:
    name: ${spring.application.name}
    links:
      - github: http://mygithub.com